ALTER TABLE players
ADD COLUMN rating DOUBLE PRECISION NOT NULL DEFAULT 1500.0,
ADD COLUMN deviation DOUBLE PRECISION NOT NULL DEFAULT 350.0,
ADD COLUMN volatility DOUBLE PRECISION NOT NULL DEFAULT 0.06;
