[package]
name = "oppai-minimax"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2024"

[dependencies]
log.workspace = true
strum.workspace = true
smallvec.workspace = true
oppai-field = { path = "../field" }
oppai-common = { path = "../common" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossbeam.workspace = true
num_cpus.workspace = true

[dev-dependencies]
criterion.workspace = true
rand.workspace = true
rand_xoshiro.workspace = true
env_logger.workspace = true
oppai-test-images = { path = "../test-images" }

[[bench]]
name = "minimax_benchmark"
path = "src/minimax_benchmark.rs"
harness = false
